import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styled, { css } from 'styled-components';
import { DailyUI } from '../components/DailyUI';

const LabelMixin = css`
  color: #ffffff;
  margin: 0;
  padding: 0;
`;

const Header = styled.header`
  display: flex;
  flex-direction: column;
  margin: 175px 100px 50px;

  > h1 {
    ${LabelMixin}
    margin-top: 20px;

    font-family: Clash Display;
    font-style: normal;
    font-weight: 500;
    font-size: 96px;
    line-height: 118px;
  }
`;

const TopRow = styled.div`
  display: flex;
  flex-direction: row;
  column-gap: 20px;
`;

const LabelStrong = styled.h3`
  ${LabelMixin}

  font-family: Switzer;
  font-style: normal;
  font-weight: 600;
  font-size: 18px;
  line-height: 24px;
  text-transform: uppercase;
`;

const Label = styled.h3`
  ${LabelMixin}

  font-family: Switzer;
  font-style: normal;
  font-weight: normal;
  font-size: 18px;
  line-height: 24px;
`;

const LargeLabel = styled.h2`
  ${LabelMixin}
  margin-right: 6px;

  font-family: Clash Display;
  font-style: normal;
  font-weight: normal;
  font-size: 36px;
  line-height: 44px;
  text-transform: uppercase;
`;

const LargeLabelStrong = styled.h2`
  ${LabelMixin}

  font-family: Clash Display;
  font-style: normal;
  font-weight: 600;
  font-size: 36px;
  line-height: 44px;
`;

const BottomRow = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  margin-top: 38px;
`;

const Group = styled.div``;

const Left = styled.div`
  display: flex;
  flex-direction: row;
  column-gap: 31px;
`;

const Right = styled.div`
  display: flex;
  flex-direction: row;
`;

const MainLayout = styled.main`
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-rows: auto;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Anne Shackelford Projects</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header>
        <TopRow>
          <LabelStrong>Start Date</LabelStrong>
          <Label>02.02.22</Label>
        </TopRow>
        <h1>DailyUI CHALLENGE</h1>
        <BottomRow>
          <Left>
            <Group>
              <LabelStrong>Designer</LabelStrong>
              <Label>Emilie Durand</Label>
            </Group>
            <Group>
              <LabelStrong>Developer</LabelStrong>
              <Label>Anne Shackelford</Label>
            </Group>
          </Left>
          <Right>
            <LargeLabel>count</LargeLabel>
            <LargeLabelStrong>001</LargeLabelStrong>
          </Right>
        </BottomRow>
      </Header>
      <MainLayout>
        <Link href='/signup' passHref>
          <a>
            <DailyUI
              backgroundColor={'#d0dcd1'}
              color={'#546f50'}
              number={'001'}
              name='Sign Up'
            />
          </a>
        </Link>
      </MainLayout>
    </div>
  );
};

export default Home;
